// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1K4hJQBQwtCG8MoSVotXEbypGT6152Rs',
    appId: '1:635171467823:web:dd96c42f2f912923990cda',
    messagingSenderId: '635171467823',
    projectId: 'frego-47086',
    authDomain: 'frego-47086.firebaseapp.com',
    storageBucket: 'frego-47086.firebasestorage.app',
    measurementId: 'G-PBR2W0618N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB938IRECgLTyUABPEDHtApHiYdGn4B0ms',
    appId: '1:635171467823:android:16f77eb40aadcd50990cda',
    messagingSenderId: '635171467823',
    projectId: 'frego-47086',
    storageBucket: 'frego-47086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4K3wNppfg4sG7NmyWbw5Of6PUZGl_w64',
    appId: '1:635171467823:ios:6f4466501927ece0990cda',
    messagingSenderId: '635171467823',
    projectId: 'frego-47086',
    storageBucket: 'frego-47086.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4K3wNppfg4sG7NmyWbw5Of6PUZGl_w64',
    appId: '1:635171467823:ios:6f4466501927ece0990cda',
    messagingSenderId: '635171467823',
    projectId: 'frego-47086',
    storageBucket: 'frego-47086.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1K4hJQBQwtCG8MoSVotXEbypGT6152Rs',
    appId: '1:635171467823:web:90ea869c5247a37b990cda',
    messagingSenderId: '635171467823',
    projectId: 'frego-47086',
    authDomain: 'frego-47086.firebaseapp.com',
    storageBucket: 'frego-47086.firebasestorage.app',
    measurementId: 'G-H2W7SFYVBT',
  );
}
