// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU48ypLBtNdA991_RTOmFilCEuMTcA7TU',
    appId: '1:729843070412:web:0b5ec7c2c29b63ebcad969',
    messagingSenderId: '729843070412',
    projectId: 'freego-edb69',
    authDomain: 'freego-edb69.firebaseapp.com',
    storageBucket: 'freego-edb69.firebasestorage.app',
    measurementId: 'G-W6S1M6PD3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mTT0SnQq9DBUiPPzYYoCMs0z_xX3fTY',
    appId: '1:729843070412:android:a2d57a6869b83624cad969',
    messagingSenderId: '729843070412',
    projectId: 'freego-edb69',
    storageBucket: 'freego-edb69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tm0nxvWwrP0VaXXfnpC2gbadpI6BZmU',
    appId: '1:729843070412:ios:43c3e2f21247410ecad969',
    messagingSenderId: '729843070412',
    projectId: 'freego-edb69',
    storageBucket: 'freego-edb69.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2tm0nxvWwrP0VaXXfnpC2gbadpI6BZmU',
    appId: '1:729843070412:ios:43c3e2f21247410ecad969',
    messagingSenderId: '729843070412',
    projectId: 'freego-edb69',
    storageBucket: 'freego-edb69.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU48ypLBtNdA991_RTOmFilCEuMTcA7TU',
    appId: '1:729843070412:web:21bc59e39d4b0416cad969',
    messagingSenderId: '729843070412',
    projectId: 'freego-edb69',
    authDomain: 'freego-edb69.firebaseapp.com',
    storageBucket: 'freego-edb69.firebasestorage.app',
    measurementId: 'G-9G5LGQWJ4B',
  );

}
